---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8761/eureka/,http://eureka-secondary:8762/eureka/,http://eureka-tertiary:8763/eureka/
