info:
  app:
    name: Telegram Bot Ryanair
    description: Ryanair bot for Telegram
    projectVersion: ${project.version}
    timestamp: ${timestamp}
    scmVersion: ${buildNumber}

routesApi:
  url: https://api.ryanair.com/core/3/routes/

schedulesApi:
  url: https://api.ryanair.com/timetable/3/schedules/{departure}/{arrival}/years/{year}/months/{yearMonth}

airportApi:
    url: https://api.ryanair.com/core/3/airports/

endpoints:
  health:
    sensitive: false

middleware:
  auth:
    header:
      name: X-API-AUTH-KEY

ryanair:
  token: 506346062:AAHPvBprq65xTow0cBsls5VS88FZyCeLO20
  user: ryanair
  commandservice:
    url: http://localhost:8092/commands

